FROM golang:latest as build

ENV GO111MODULE=on \
    CGO_ENABLE=1 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY="https://goproxy.cn,direct"

WORKDIR /go/src/acmsvr
ADD . .
RUN go mod download
RUN go build -o acmsvr

#FROM scratch as prod
FROM ubuntu:18.04 as runner

WORKDIR /acmsvr/run

ENV LD_LIBRARY_PATH ./cgolib
RUN ldconfig

COPY --from=build /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=build /go/src/acmsvr/acmsvr .
COPY --from=build /go/src/acmsvr/conf ./conf
# COPY --from=build /go/src/acmsvr/app/middleware/lic_cgo/liblicense.so ./cgolib/

EXPOSE 9088
CMD ["./acmsvr"]
